[package]
name = "protanki-server"
version = "2.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1.28.0", features = ["rt", "rt-multi-thread", "sync", "fs", "net", "time", "macros"] }
protocol = { path = "protocol" }
thiserror = "1.0.40"
