name: Publish release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Change version'
        run: |
          sed -i "s/version = \".*\"/version = \"${{ github.event.inputs.version }}\"/g" build.gradle.kts
          sed -i "s/gitBranch = \".*\"/gitBranch = \"${GITHUB_REF#refs/heads/}\"/g" build.gradle.kts
          sed -i "s/gitCommitHash = \".*\"/gitCommitHash = \"$(git rev-parse HEAD)\"/g" build.gradle.kts
      - name: 'Create ZIP distribution'
        run: ./gradlew distZip --no-daemon
#      - uses: actions/upload-artifact@v3
#        with:
#          name: ProTankiServer-${{ github.event.inputs.version }}-dist.zip
#          path: build/distributions/ProTankiServer-*.zip
      - name: 'Publish release'
        run: |
          gh release create "v${{ github.event.inputs.version }}" -t "ProTanki Server v${{ github.event.inputs.version }}" --generate-notes "build/distributions/ProTankiServer-*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Commit changes'
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add build.gradle.kts
          git commit -m "build(version): Release version ${{ github.event.inputs.version }}" -m "Created by: ${{ github.event.sender.login }}" -m "[ci skip]"
          git pull origin ${{ github.event.ref }} --rebase
          git push origin ${{ github.event.ref }}
